package Controllers;

public enum State {
    REPORT, UPDATE_TRIP,ADD_TRIP,UPDATE_TRAIN, ADD_TRAIN, REGISTER, LOGIN, USER_HOME, ADMIN_HOME,
    VIEW_ALL_TRAINS, BOOK_TKT, DELETE_TKT, EDIT_INFO, VIEW_ALL_TRIPS
}
